data:
  raw_data_path: 'data/raw/iris.csv'
  processed_data_path: 'data/processed/iris_processed.csv'

model:
  type: 'RandomForestClassifier'
  params:
    n_estimators: 100
    random_state: 42

train:
  test_size: 0.2
  random_state: 42

logs:
  path: 'logs/experiment_logs.json'

models:
  path: 'models/'